[package]
name = "mapping"
version = "0.1.0"
edition = "2024"
[lib]
proc-macro = true

[dependencies]
faststr = "0.2.32"
heck = "0.5.0"
linked-hash-map = "0.5.6"
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = "2.0.111"
