[package]
name = "mymacros"
version = "0.1.0"
edition = "2024"


[dependencies]
mapping = { path = "../mapping" }
macros = { path = "../macros" }
syn = { version = "2.0.106", features = ["full", "extra-traits"] }
volo-http = "0.4.3"
